#!/usr/bin/env python3
"""Regenerate docs/truthfiles/functions.md from source docstrings via static AST parsing."""

from __future__ import annotations

import ast
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = REPO_ROOT / "src" / "toymc_cosmic"
OUTPUT_PATH = REPO_ROOT / "docs" / "truthfiles" / "functions.md"

DOCUMENTABLE = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)


class Entity(NamedTuple):
    lineno: int
    qualname: str
    first_line: str


def first_docstring_line(node: ast.AST) -> str:
    """Return the first line of node's docstring, or a missing-docstring marker."""
    docstring = ast.get_docstring(node, clean=True)
    if docstring is None:
        return "(missing docstring)"
    return docstring.strip().splitlines()[0].strip()


def collect_entities(tree: ast.Module) -> list[Entity]:
    """Collect module-level functions/classes and one level of class methods; returns them sorted by line."""
    entities: list[Entity] = []
    for node in tree.body:
        if isinstance(node, DOCUMENTABLE):
            entities.append(Entity(node.lineno, node.name, first_docstring_line(node)))
        if isinstance(node, ast.ClassDef):
            for member in node.body:
                if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    qualname = f"{node.name}.{member.name}"
                    entities.append(Entity(member.lineno, qualname, first_docstring_line(member)))
    entities.sort(key=lambda entity: entity.lineno)
    return entities


def ordered_source_files() -> list[Path]:
    """Return src/toymc_cosmic/*.py files with core modules before gui/ modules, alphabetical within each."""
    core_files = sorted(p for p in SRC_ROOT.glob("*.py"))
    gui_files = sorted(p for p in (SRC_ROOT / "gui").glob("*.py"))
    return core_files + gui_files


def render_file_section(path: Path) -> str:
    """Render one file's Markdown section listing its documentable entities."""
    tree = ast.parse(path.read_text(), filename=str(path))
    entities = collect_entities(tree)
    relative_path = path.relative_to(REPO_ROOT)
    lines = [f"## {relative_path}", ""]
    if not entities:
        lines.append("(no module-level functions or classes)")
    else:
        for entity in entities:
            lines.append(f"- `{entity.qualname}` (L{entity.lineno}): {entity.first_line}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Write docs/truthfiles/functions.md from every src/toymc_cosmic source file."""
    header = (
        "# Functions\n\n"
        "_Auto-generated by `scripts/gen_function_truthfile.py` — do not hand-edit. "
        "Regenerate after any docstring or function signature change:_\n"
        "`.venv/bin/python scripts/gen_function_truthfile.py`\n\n"
    )
    sections = [render_file_section(path) for path in ordered_source_files()]
    OUTPUT_PATH.write_text(header + "\n".join(sections))
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
